version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ni-covid-tweets"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bhyx6qie1x2q"
s3_prefix = "ni-covid-tweets"
region = "eu-west-2"
profile = "codeandnumbers"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
